#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DogWalkies.Resource", IsApplication=true)]

namespace DogWalkies
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int addcircleIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int buttonCamera = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int buttonEnabled = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int buttonEnabledMini = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int buttonMini = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int buttonPressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int buttonPressedMini = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int cameraIcon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int cameraIconPressed = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int chart = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int dogProfileImageMainView = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int dogProfileImageMainViewTransparent = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int DogWalkiesLogo = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int draftIcon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int editcircleIcon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int editIcon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int editIcon2 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int homeIcon = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Icon = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int imageIcon = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int infoIcon = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int pawIcon = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int pawIconSmall = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int walkIcon = 2130837528;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05002f
			public const int ButtonMetrics = 2131034159;
			
			// aapt resource value: 0x7f050013
			public const int ButtonMonth = 2131034131;
			
			// aapt resource value: 0x7f050008
			public const int ButtonProfile = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int ButtonStartWalk = 2131034121;
			
			// aapt resource value: 0x7f05002e
			public const int ButtonViewAlbum = 2131034158;
			
			// aapt resource value: 0x7f050016
			public const int ButtonWalkReminder = 2131034134;
			
			// aapt resource value: 0x7f050012
			public const int ButtonWeek = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int ButtonYear = 2131034132;
			
			// aapt resource value: 0x7f050034
			public const int EditTextAgeData = 2131034164;
			
			// aapt resource value: 0x7f050036
			public const int EditTextBirthdateData = 2131034166;
			
			// aapt resource value: 0x7f050032
			public const int EditTextBreedData = 2131034162;
			
			// aapt resource value: 0x7f050038
			public const int EditTextColorData = 2131034168;
			
			// aapt resource value: 0x7f05003a
			public const int EditTextGenderData = 2131034170;
			
			// aapt resource value: 0x7f05003c
			public const int EditTextMicrochipData = 2131034172;
			
			// aapt resource value: 0x7f05002c
			public const int EditTextOwnerNameData = 2131034156;
			
			// aapt resource value: 0x7f050007
			public const int ImageButtonAddDogProfileImage = 2131034119;
			
			// aapt resource value: 0x7f05000b
			public const int ImageButtonCamera = 2131034123;
			
			// aapt resource value: 0x7f05002d
			public const int ImageButtonEditDogOwnerName = 2131034157;
			
			// aapt resource value: 0x7f050029
			public const int ImageButtonEditIcon = 2131034153;
			
			// aapt resource value: 0x7f050015
			public const int ImageViewChart = 2131034133;
			
			// aapt resource value: 0x7f050004
			public const int ImageViewDWIcon = 2131034116;
			
			// aapt resource value: 0x7f05000c
			public const int ImageViewDWLogo = 2131034124;
			
			// aapt resource value: 0x7f050006
			public const int ImageViewDogProfile = 2131034118;
			
			// aapt resource value: 0x7f050026
			public const int ImageViewDraftIcon = 2131034150;
			
			// aapt resource value: 0x7f05000f
			public const int ImageViewPaw = 2131034127;
			
			// aapt resource value: 0x7f050002
			public const int ImageViewPawPrintIcon = 2131034114;
			
			// aapt resource value: 0x7f050011
			public const int LinearLayoutGraphButtons = 2131034129;
			
			// aapt resource value: 0x7f050024
			public const int LinearLayoutNotesSection = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int LinearLayoutNotesTopBar = 2131034149;
			
			// aapt resource value: 0x7f05000a
			public const int RelativeLayoutCameraBar = 2131034122;
			
			// aapt resource value: 0x7f050001
			public const int RelativeLayoutDogNameBar = 2131034113;
			
			// aapt resource value: 0x7f050030
			public const int RelativeLayoutDogProfile = 2131034160;
			
			// aapt resource value: 0x7f050005
			public const int RelativeLayoutDogProfileBar = 2131034117;
			
			// aapt resource value: 0x7f050010
			public const int RelativeLayoutDogProfileImage = 2131034128;
			
			// aapt resource value: 0x7f05001b
			public const int RelativeLayoutLastWalked = 2131034139;
			
			// aapt resource value: 0x7f050028
			public const int RelativeLayoutNotesContent = 2131034152;
			
			// aapt resource value: 0x7f050018
			public const int RelativeLayoutReminder = 2131034136;
			
			// aapt resource value: 0x7f05001e
			public const int RelativeLayoutTotalDistance = 2131034142;
			
			// aapt resource value: 0x7f050021
			public const int RelativeLayoutTotalTime = 2131034145;
			
			// aapt resource value: 0x7f05000e
			public const int RelatvieLayoutDogNameBar = 2131034126;
			
			// aapt resource value: 0x7f050033
			public const int TextViewAge = 2131034163;
			
			// aapt resource value: 0x7f050035
			public const int TextViewBirthdate = 2131034165;
			
			// aapt resource value: 0x7f050017
			public const int TextViewBorderTopHack = 2131034135;
			
			// aapt resource value: 0x7f050031
			public const int TextViewBreed = 2131034161;
			
			// aapt resource value: 0x7f050037
			public const int TextViewColor = 2131034167;
			
			// aapt resource value: 0x7f050003
			public const int TextViewDogFirstName = 2131034115;
			
			// aapt resource value: 0x7f050039
			public const int TextViewGender = 2131034169;
			
			// aapt resource value: 0x7f05001c
			public const int TextViewLastWalked = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int TextViewLastWalkedData = 2131034141;
			
			// aapt resource value: 0x7f05003b
			public const int TextViewMicrochip = 2131034171;
			
			// aapt resource value: 0x7f050027
			public const int TextViewNotes = 2131034151;
			
			// aapt resource value: 0x7f05002b
			public const int TextViewOwnerName = 2131034155;
			
			// aapt resource value: 0x7f050019
			public const int TextViewReminder = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int TextViewReminderData = 2131034138;
			
			// aapt resource value: 0x7f05001f
			public const int TextViewTotalDistance = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int TextViewTotalDistanceData = 2131034144;
			
			// aapt resource value: 0x7f050022
			public const int TextViewTotalTime = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int TextViewTotalTimeData = 2131034147;
			
			// aapt resource value: 0x7f050000
			public const int mainScrollView = 2131034112;
			
			// aapt resource value: 0x7f05000d
			public const int metricsScrollView = 2131034125;
			
			// aapt resource value: 0x7f05002a
			public const int profileScrollView = 2131034154;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Metrics = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Profile = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int GeneralError = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int SavedToGallery = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
