#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DogWalkies.Resource", IsApplication=true)]

namespace DogWalkies
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int addcircleIcon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int buttonCamera = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int buttonEnabled = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int buttonPressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int cameraIcon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int cameraIconPressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int DogWalkiesLogo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int draftIcon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int editIcon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int editIcon2 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int homeIcon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Icon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int imageIcon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int infoIcon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int pawIcon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int sheltieMainView = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050008
			public const int ButtonProfile = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int ButtonStartWalk = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int ImageButtonAddDogProfileImage = 2131034119;
			
			// aapt resource value: 0x7f05000b
			public const int ImageButtonCamera = 2131034123;
			
			// aapt resource value: 0x7f050004
			public const int ImageViewDWIcon = 2131034116;
			
			// aapt resource value: 0x7f05000c
			public const int ImageViewDWLogo = 2131034124;
			
			// aapt resource value: 0x7f050002
			public const int ImageViewPawPrintIcon = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int ImageViewSheltie = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int RelativeLayoutCameraBar = 2131034122;
			
			// aapt resource value: 0x7f050001
			public const int RelativeLayoutDogNameBar = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int RelativeLayoutDogProfileBar = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int TextViewDogFirstName = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int mainScrollView = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
